from setuptools import setup, find_packages

setup(
    name="btools",
    version="1.0.0",
    author="Blake Bian",
    author_email="your.email@example.com",
    description="一个实用的工具类和函数集合",
    long_description="一个用于Python项目的实用工具类和函数集合，包括日志记录、配置管理、数据验证和类型转换功能。",
    long_description_content_type="text/markdown",
    url="https://example.com",
    packages=find_packages(),
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Intended Audience :: Developers",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
    python_requires='>=3.8',
    install_requires=[
        'pyyaml~=6.0.3',
        'python-dotenv~=1.0.0',
        'requests~=2.32.4',
        'requests-toolbelt~=1.0.0',
        'requests-cache~=1.3.0',
        'urllib3~=2.2.0',
        'openpyxl~=3.1.2',
        'selenium~=4.26.0',
        'playwright~=1.44.0',
        'webdriver-manager~=4.0.0',
        'Appium-Python-Client~=2.11.1',
        'paramiko~=3.4.0',
        'PySocks~=1.7.1',
        'httplib2~=0.22.0',
        'cryptography~=39.0.0',
        'redis~=4.5.0',
        'pymysql~=1.1.0',
        'psutil~=5.9.0',
        'Pillow~=9.5.0',
        'numpy~=1.24.4',
        'qrcode[pil]~=7.4.2',
        'pyzbar~=0.1.9',
        'Jinja2~=3.1.0',
        'tiktoken~=0.3.3',
        'jsonpath-ng~=1.6.0',
        'fastapi~=0.104.1',
        'uvicorn[standard]~=0.24.0',
        'pydantic~=2.5.0',
        'pydantic-settings~=2.1.0',
    ],
)
