# 自动化测试工具类
from .appiumutils import AppiumUtils
from .fakerutils import (
    FakerUtils,
    generate_test_data,
    random_address,
    random_bank_card,
    random_boolean,
    random_company,
    random_credit_card,
    random_date,
    random_datetime,
    random_email,
    random_float,
    random_id_card,
    random_integer,
    random_ip,
    random_name,
    random_order,
    random_phone,
    random_position,
    random_product,
    random_string,
    random_url,
    random_user,
    random_user_agent,
)
from .playwrightutils import PlaywrightUtils
from .seleniumutils import SeleniumUtils

__all__ = [
    "SeleniumUtils",
    "PlaywrightUtils",
    "AppiumUtils",
    "FakerUtils",
    "random_string",
    "random_integer",
    "random_float",
    "random_boolean",
    "random_date",
    "random_datetime",
    "random_email",
    "random_phone",
    "random_name",
    "random_address",
    "random_company",
    "random_position",
    "random_id_card",
    "random_bank_card",
    "random_ip",
    "random_url",
    "random_user_agent",
    "random_credit_card",
    "random_user",
    "random_product",
    "random_order",
    "generate_test_data",
]
